export const EXCURSION_ESCOLAR_PRIMARIA = [
  {
    img: '/img/Escolar/Excursion-De-Campo/paracasExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Paracas - Excursion Primaria',
    title: 'Paracas',
    description: 'Tour Ecológico a la Reserva Nacional, dentro de la Península en la Bahía de Paracas. Tour con reconocimiento de avifauna marina. Historia milenaria cultura Paracas asombrosos ceramistas e increíbles tejedores que vivieron en este desierto hace 2000 años. Dentro de la Reserva observaremos el famoso paisaje lunar y los naturales cortes terrestres.',
    price: 'Desde S/99',
    duration: 'Full Day de 12 a 15 horas',
    additionalServices: 'Tour Maritimo S/35',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/lunahuanaExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Lunahuana - Excursion Primaria',
    title: 'Lunahuana',
    description: 'Verde Valle de la sierra de Lima, circuito ecológico por Cañete, Cerro Azul. Pueblo de piratas, Castillo Unanue, Ciudadela Inka de Inkawasi, puente colgante de Catapalla. Zona agrícola, visita a vitivinícolas artesanales y a la zona apícola. Lunahuaná goza de un clima preferente de sol 10 meses al año.',
    price: 'Desde S/75',
    duration: 'Full Day de 09 a 12 horas',
    additionalServices: 'Almuerzo Campestre S/20',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/bandurriaExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Bandurria / Albufera - Excursion Primaria',
    title: 'Bandurria / Albufera',
    description: 'Centro arqueológico con más de 4000 años de historia con hermosa vista frente al mar a la Laguna de Paraíso, visita al Balcón de Huaura pequeño e histórico pueblo. Laguna de la Albufera de Medio Mundo en Vegueta o Castillo de Chancay de estilo medieval y con interesantísimo museo de la cultura Chancay, piscinas y otros atractivos más.',
    price: 'Desde S/70',
    duration: 'Full Day de 09 a 12 horas',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/caneteExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Cañete / Chincha - Excursion Primaria',
    title: 'Cañete / Chincha',
    description: 'Tour Ecológico al ser de Lima visitando la zona rural campestre de Mala, Azpitia o San Antonio, y la zona del litoral en Cerro Azul, en Chincha visita a Gracia Prado casa de la Melchorita, cómo se elabora el vino artesanal y conocer de cerca el folklore negro peruano.',
    price: 'Desde S/65',
    duration: 'Full Day de 12 a 15 horas',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/lachayExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Lomas de Lachay - Excursion Primaria',
    title: 'Lomas de Lachay',
    description: 'Un Oasis en el desierto norteño, trekking en la Reserva Natural en libre contacto con la naturaleza, lomas forradas de vegetación solo de julio a noviembre, y donde vive la taruca, el águila, el zorro lomo plateado y otros. Visita combinable con el Castillo de Chancay o zona ecológica de Huaral.',
    price: 'Desde S/65',
    duration: 'Full Day de 09 a 12 horas',
    additionalServices: 'Consultar por adicionales y promociones',
  }
]

export const EXCURSION_ESCOLAR_SECUNDARIA = [
  {
    img: '/img/Escolar/Excursion-De-Campo/paracasExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Paracas - Excursion Primaria',
    title: 'Paracas',
    description: 'Tour Ecológico a la Reserva Nacional, dentro de la Península en la Bahía de Paracas. Tour con reconocimiento de avifauna marina. Historia milenaria cultura Paracas asombrosos ceramistas e increíbles tejedores que vivieron en este desierto hace 2000 años. Dentro de la Reserva observaremos el famoso paisaje lunar y los naturales cortes terrestres.',
    price: 'Desde S/89',
    duration: 'Full Day de 12 a 15 horas',
    additionalServices: 'Tour Maritimo S/35',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/lunahuanaExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Lunahuana - Excursion Primaria',
    title: 'Lunahuana',
    description: 'Verde Valle de la sierra de Lima, circuito ecológico por Cañete, Cerro Azul. Pueblo de piratas, Castillo Unanue, Ciudadela Inka de Inkawasi, puente colgante de Catapalla. Zona agrícola, visita a vitivinícolas artesanales y a la zona apícola. Lunahuaná goza de un clima preferente de sol 10 meses al año.',
    price: 'Desde S/75',
    duration: 'Full Day de 09 a 12 horas',
    additionalServices: 'Almuerzo Campestre S/20',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/bandurriaExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Bandurria / Albufera - Excursion Primaria',
    title: 'Bandurria / Albufera',
    description: 'Centro arqueológico con más de 4000 años de historia con hermosa vista frente al mar a la Laguna de Paraíso, visita al Balcón de Huaura pequeño e histórico pueblo. Laguna de la Albufera de Medio Mundo en Vegueta o Castillo de Chancay de estilo medieval y con interesantísimo museo de la cultura Chancay, piscinas y otros atractivos más.',
    price: 'Desde S/65',
    duration: 'Full Day de 09 a 12 horas',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/caneteExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Cañete / Chincha - Excursion Primaria',
    title: 'Cañete / Chincha',
    description: 'Tour Ecológico al ser de Lima visitando la zona rural campestre de Mala, Azpitia o San Antonio, y la zona del litoral en Cerro Azul, en Chincha visita a Gracia Prado casa de la Melchorita, cómo se elabora el vino artesanal y conocer de cerca el folklore negro peruano.',
    price: 'Desde S/65',
    duration: 'Full Day de 12 a 15 horas',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/lachayExcursionPrimaria.webp',
    altImg: 'Imagen de Tour Lomas de Lachay - Excursion Primaria',
    title: 'Lomas de Lachay',
    description: 'Un Oasis en el desierto norteño, trekking en la Reserva Natural en libre contacto con la naturaleza, lomas forradas de vegetación solo de julio a noviembre, y donde vive la taruca, el águila, el zorro lomo plateado y otros. Visita combinable con el Castillo de Chancay o zona ecológica de Huaral.',
    price: 'Desde S/65',
    duration: 'Full Day de 09 a 12 horas',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Excursion-De-Campo/caralExcursionSecundaria.webp',
    altImg: 'Imagen de Tour Caral / Supe - Excursion Primaria',
    title: 'Caral / Supe',
    description: 'Redescubrimiento de la historia mundial al conocer ahora que Caral es la ciudad más antigua de América. Época similar a Egipto y Mesopotamia. Verán plazas y templos, norte Chico conociendo super puerto de piratas. Guía de sitio y guía de tour. Mínimo 12 horas de duración para visita completa.',
    price: 'Desde S/65',
    duration: 'Full Day de 09 a 12 horas',
    additionalServices: 'Consultar por adicionales y promociones',
  }
]

export const VIAJE_ESCOLAR_TERRESTRE = [
  {
    img: '/img/Escolar/Viaje-De-Estudios/huaylasViajeTerrestre.webp',
    altImg: 'Imagen de Callejon de Huaylas - Viaje Escolar Terrestre',
    title: 'Callejon de Huaylas',
    description: 'Huaraz, Callejón de Huaylas, Callejón de Conchucos, Yungay. Caraz, Llanganuco, Chavín de Huántar, Nevado de Pastoruri. City tour en la ciudad de la presunción, baños.',
    include: 'Transporte en Bus doble eje, Hotel baño privado con TV, Alimentación completa, Tours con Guías y Tickets',
    price: 'Desde S/599',
    duration: '04 Días Hotel ⭐⭐⭐',
    additionalServices: '04 Dias Hotel ⭐⭐⭐⭐ desde S/709',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/chanchamayoViajeTerrestre.webp',
    altImg: 'Imagen de Chanchamayo / Selva Central - Viaje Escolar Terrestre',
    title: 'Chanchamayo / Selva Central',
    description: 'Ciudad y Valle, distrito de Miraflores, Llamaquizu y Chontabamba, Tunquicueva caverna con estalactitas, casa Botteger Treu, nativa comunidad Yaneshika Shacchopen, orquidario, tribu Ashaninka Pampa Michi, catarata del Tirol, visita social opcional.',
    include: 'Transporte, Hotel, Alimentación completa',
    price: 'Desde S/650',
    duration: '04 Días Hotel ⭐⭐⭐',
    additionalServices: '05 Dias Hotel ⭐⭐⭐ desde S/709',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/mantaroViajeTerrestre.webp',
    altImg: 'Imagen de Valle del Mantaro - Viaje Escolar Terrestre',
    title: 'Valle del Mantaro',
    description: 'Huancayo, Cerrito La Libertad, criaderos de truchas, Ingenio, Convenio de Sta Rosa de Ocopa, Laguna de Paca, Laguna Jauja. Opcional combinado con visita a Tarma y Guagapo.',
    include: 'Transporte Privado o Interprovincial con baño, Hotel baño privado, TV, Alimentación.',
    price: 'Desde S/490',
    duration: '03 Días Hotel ⭐⭐⭐',
    additionalServices: '04 Dias Hotel ⭐⭐⭐ desde S/599',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/surChicoViajeTerrestre.webp',
    altImg: 'Imagen de Sur Chico - Viaje Escolar Terrestre',
    title: 'Sur Chico',
    description: 'Tour Maritimo a Islas Ballestas para conocer lobos marinos, pinguinos y cormoranes, el enigmático Candelabro y la Reserva Nacional, cuna de la milenaria Cultura Paracas, Ica, excusión a la laguna de Huacachina, Tour de aventura en las Dunas.',
    include: 'Transporte Privado o Interprovincial con baño, Hotel baño privado, TV, Alimentación.',
    price: 'Desde S/490',
    duration: '03 Días Hotel ⭐⭐⭐',
    additionalServices: '04 Dias Hotel ⭐⭐⭐ desde S/599',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/lunahuanaViajeTerrestre.webp',
    altImg: 'Imagen de Lunahuana / Cañete / Chilca - Viaje Escolar Terrestre',
    title: 'Lunahuana / Cañete / Chilca',
    description: 'Chilca paleolítica, Cerro Azul playa de surfistas, Valle de Lunahuaná Abundante rio y mucho sol. Goza de un excelente clima, muy buena comida, ruinas de Inkawasi, vitivinicolasa, Iglesia, casa embrujada, Puente Colgante Catapalla, a elegir hotel o camping c/sin piscina.',
    include: 'Transporte Privado o Interprovincial con baño, Hotel baño privado, TV, Alimentación.',
    price: 'Desde S/299',
    duration: '02 Días Hotel ⭐⭐⭐',
    additionalServices: '03 Dias Hotel ⭐⭐⭐ desde S/359',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/norteChicoViajeTerrestre.webp',
    altImg: 'Imagen de Norte Chico - Viaje Escolar Terrestre',
    title: 'Norte Chico',
    description: 'Didáctica visita a Caral en Supe, surgió 5000 años increible civilización de epoca egipcia, Chancay, Oasis de Lachay, recreación en la Albufera de medio mundo, avifauna y especies de agua dulce y salada, botecitos. Visita al Balcón de Huaura donde San Martín proclamo la independencia.',
    include: 'Transporte Privado o Interprovincial con baño, Hotel baño privado, TV, Alimentación.',
    price: 'Desde S/280',
    duration: '02 Días Hotel ⭐⭐⭐',
    additionalServices: '03 Dias Hotel ⭐⭐⭐ desde S/350',
  },
]

export const VIAJE_ESCOLAR_AEREO = [
  {
    img: '/img/Escolar/Viaje-De-Estudios/tumbesViajeAereo.webp',
    altImg: 'Imagen de Tumbes / Piura - Viaje Escolar Aéreo',
    title: 'Tumbes / Piura',
    description: 'Norte grande, Manglares de Tumbes hábitat natural del cocodrilo y observación cruce del agua dulce y el mar, playa de Zorritos, Catacaos desierto de Sechura, Punta Sal, balneario playas de arena blanca, Mancora, Pocitas, Organos y El Ñuro a nadar con las tortugas marinas.',
    include: 'Transporte aéreo, Hotel baño privado con TV, Alimentación completa y tours.',
    price: 'Desde $490',
    duration: '04 Días Hotel ⭐⭐⭐',
    additionalServices: '05 Dias Hotel ⭐⭐⭐ desde S/590',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/cajamarcaViajeAereo.webp',
    altImg: 'Imagen de Cajamarca / Sierra Norte - Viaje Escolar Aéreo',
    title: 'Cajamarca / Sierra Norte',
    description: 'City Tour por la bella ciudad de Cajamarca, Plaza de Armas, Catedral Torres, Otuzco - Campiña - Llacanora, Cumbemayo, Baños del Inca.',
    include: 'Transporte aéreo, Hotel baño privado con TV, Alimentación completa y tours.',
    price: 'Desde $390',
    duration: '03 Días Hotel ⭐⭐⭐',
    additionalServices: '04 Dias Hotel ⭐⭐⭐ desde $490',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/tarapotoViajeAereo.webp',
    altImg: 'Imagen de Tarapoto Paraiso - Viaje Escolar Aéreo',
    title: 'Tarapoto Paraiso',
    description: 'Visita a la pintoresca ciudad de Lamas, Catarata Ahuashiyacu, Ciudad de Rioja. Tour Laguna Azul de impresionante belleza natural, una aventura para llegar allí a través de la Selva Peruana.',
    include: 'Transporte aéreo, Hotel baño privado con TV, Alimentación completa y tours.',
    price: 'Desde $390',
    duration: '03 Días Hotel ⭐⭐⭐',
    additionalServices: '04 Dias Hotel ⭐⭐⭐ desde $490',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/cuscoViajeAereo.webp',
    altImg: 'Imagen de Cusco Magico / Cusco Mapi - Viaje Escolar Aéreo',
    title: 'Cusco Magico / Cusco Mapi',
    description: 'Maravilla del mundo, Cusco ciudad más ruinas aledañas: Kenko, Sacsayhuamán, Tambomachay. Valle Sagrado; Ollantaytambo y Chincheros, feria de Pisac. Ciudadela Sagrada de Machu Picchu. Dos opciones diferentes de visita, danzas Qosqo, Koricancha. Ofrecemos doble exposición previa de todo el recorrido. ',
    include: 'Transporte aéreo, Hotel baño privado con TV, Alimentación completa y tours.',
    price: 'Desde $490',
    duration: '04 Días Hotel ⭐⭐⭐',
    additionalServices: '05 Dias Hotel ⭐⭐⭐ desde $590',
  },
  {
    img: '/img/Escolar/Viaje-De-Estudios/chiclayoViajeAereo.webp',
    altImg: 'Imagen de Chiclayo / Trujillo - Viaje Escolar Aéreo',
    title: 'Chiclayo / Trujillo',
    description: 'Señor de Sipán, tumbas y nuevo museo. Pirámides de Tucume, y en Ferreñafe museo Sican, Lambayeque visita al Museo de tumbas reales fábrica de Kingkon San Roque, Santuario del Bosque de Pomac en la provincia de Ferreñafe, Trujillo. Ciudadela Chan Chan, zona Chimú Templo del Sol y la Luna, zona Moche, City Tour y playa Huanchaco.',
    include: 'Transporte aéreo, Hotel baño privado con TV, Alimentación completa y tours.',
    price: 'Desde $490',
    duration: '04 Días Hotel ⭐⭐⭐',
    additionalServices: '05 Dias Hotel ⭐⭐⭐ desde $590',
  }
]

export const VISITA_ESCOLAR_PRIMARIA = [
  {
    img: '/img/Escolar/Visita-De-Estudios/historiaVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Museos de Historia Natural - Visita Primaria',
    title: 'Museos de Historia Natural',
    description: 'Visita guiada al museo privado de la Universidad Ricardo Palma combinamos con recreación en el Parque de la Amistad Visita guiada al Parque de las Leyendas con el Gran Parque de Lima, exposición permanente de animales disecados, fósiles y ambientación de dinosaurios.',
    price: 'Desde S/17',
    duration: 'En Bus de 45 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/cienciasVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Museos de Ciencias - Visita Primaria',
    title: 'Museos de Ciencias',
    description: 'El Parque de la Imaginación en Lima es un espacio interactivo donde la ciencia y la tecnología se fusionan con la diversión y el aprendizaje. Ofrece experiencias educativas y lúdicas que estimulan la creatividad y el pensamiento crítico en niños y adolescentes.',
    price: 'Desde S/24',
    duration: 'En Minibus de 25 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/arqueologicoVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Museos Arqueológicos - Visita Primaria',
    title: 'Museos Arqueológicos',
    description: 'Los museos arqueológicos para niños ofrecen una emocionante aventura en el pasado, donde los jóvenes exploradores pueden descubrir civilizaciones antiguas a través de exhibiciones interactivas, réplicas de artefactos y actividades educativas diseñadas para despertar su curiosidad y comprensión de la historia.',
    price: 'Desde S/16',
    duration: 'En Bus de 45 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/huacaVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Huacas de Lima - Visita Primaria',
    title: 'Huacas de Lima',
    description: 'Las huacas de Lima son como gigantescos castillos de la antigüedad. ¡Aquí los niños pueden descubrir secretos de nuestros ancestros! Pueden explorar pirámides y templos, ¡y sentirse como verdaderos arqueólogos descubriendo tesoros del pasado!',
    price: 'Desde S/17',
    duration: 'En Bus de 45 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/centroVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Centro Histórico - Visita Primaria',
    title: 'Centro Histórico',
    description: 'Ubicación Plaza mayor e importantes edificios públicos Municipalidad, Palacio de Gobierno, visita al museo filatélico, correo y Santuario de Sta. Rosa.',
    price: 'Desde S/17',
    duration: 'En Bus de 45 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/zoologicosVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Zoologicos - Visita Primaria',
    title: 'Zoologicos',
    description: 'Serpentario, jardín de las aves, caídas de Aguas, lobos de Mar, perezosos y otros mas, consulte por talleres. Parque de las Leyendas, zoológico nacional e internacional, costa, sierra, selva y laguna con hipopótamos, islas de osos.',
    price: 'Desde S/21',
    duration: 'En Bus de 45 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/planetarioVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Planetario y Pantanos - Visita Primaria',
    title: 'Planetario y Pantanos',
    description: 'Video explicativo y recorrido a pie con los Guías alrededor de los pantanos, combinamos con didáctica exposición en el planetario Solar, sobre teoría e la formación de los planetas y astros, sino no pueden cambiar por tour en Barranco, museo y tranvía.',
    price: 'Desde S/26',
    duration: 'En Bus de 45 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/granjitasVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Granjitas Ecológicas - Visita Primaria',
    title: 'Granjitas Ecológicas',
    description: 'En una granja Interactiva los niños pueden ordeñar la vaca, dar el biberón a los terneros, cabritos u ovejitas, recoger huevos o tener una breve charla de cómo sembrar y cosechar vegetales. Universidad Agraria la visita técnica y didáctica con especialistas en la materia.',
    price: 'Desde S/32',
    duration: 'En Bus de 45 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  }
]

export const VISITA_ESCOLAR_SECUNDARIA = [
  {
    img: '/img/Escolar/Visita-De-Estudios/centroIVisitaSecundaria.webp',
    altImg: 'Imagen de Tour Centro Historico I - Visita Secundaria',
    title: 'Centro Historico I',
    description: 'Citytour, Colonial y Virreinal, Plaza mayor completamente detallada, Palacio de Gobierno, Municipalidad, cambio de guardia, Correo Centro, Alameda Chabuca Granda. Catedral de Lima, museo y sala de oro del BCR, Mali y gran parque de Lima con impresionantes monumentos, la fuente china y el parque japonés.',
    price: 'Desde S/20',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/centroIIVisitaSecundaria.webp',
    altImg: 'Imagen de Tour Centro Historico II - Visita Secundaria',
    title: 'Centro Historico II',
    description: 'Citytour colonial y Republicano, Congreso de la República, museo de La Santa Sede del Tribunal de la Inquisición, casa de la Moneda (ex acuñadora) o visita la primera compañia de Bomberos de Lima. Bomba Nro 01. Plaza de Armas o tour Rimac señorial combina historia y actualidad.',
    price: 'Desde S/20',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/arqueologicoVisitaPrimaria.webp',
    altImg: 'Imagen de Tour Museos Arqueológicos - Visita Secundaria',
    title: 'Museos Arqueológicos',
    description: 'Visita guiada con fichas de estudio detalladas, Museo Nacional de Arqueología y Antropología, presenta cronológicamente las culturas Peruanas lo cual facilita al alumno entender el desarrollo de cada una Museo de la Nación, didáctico, maquetas y amplios salones de exhibición.',
    price: 'Desde S/20',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/privadoVisitaSecundaria.webp',
    altImg: 'Imagen de Tour Museos Privados - Visita Secundaria',
    title: 'Museos Privados',
    description: 'Colecciones privadas arqueológicas: Colección Mujica gallo en el Museo Oro del Perú y Armas del Mundo, impresionantes armaduras, espadas distintas épocas así como el magnífico oro chimú. Museo privado Amano Museo Larco Herrara Hoyle, Momias Cultura Norte, oro, ceramios, talleres.',
    price: 'Desde S/24',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/heroicaVisitaSecundaria.webp',
    altImg: 'Imagen de Tour Ciudades Heroicas - Visita Secundaria',
    title: 'Ciudades Heroicas',
    description: 'En este circuito se reúnen Historia, Ecología y Geografía, objetivo final por visita varía de aceurdo al grado de los alumnos. Historia, Defensa de Lima en la Guerra con Chile. Geografía, Planetario Solar, exposición elegible primaria y secundaria. Ecología, Pantanos de Villa. Industria, Museo de Electricidad. Urbanindad, Puente de los Suspiros.',
    price: 'Desde S/22',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/puertoVisitaSecundaria.webp',
    altImg: 'Imagen de Tour Puerto Real De Lima - Visita Secundaria',
    title: 'Puerto Real De Lima',
    description: 'Tour por el histórico Puerto de Lima, el Callao Antiguo, con visitas a la fortaleza del Real Felipe construida en el siglo XVIII para defender nuestra ciudad de los ataques de piratas y corsarios, combinable con visita al submarino Abtao de la Marina de Guerra o Museo Naval que alberta una colección de Miguel Grau y la Guerra con Chile.',
    price: 'Desde S/22',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/pachacamacVisitaSecundaria.webp',
    altImg: 'Imagen de Tour Pachacamac - Visita Secundaria',
    title: 'Pachacamac',
    description: 'Recorrido a pie del santuaria, visita al Templo del Sol y Vista Exterior del Acliahuasi o casa de las mamaconas, ciudadela religiosa de origen Itchma, en el nuevo museo guarda el famoso idolo de madera vista exterior del templo provisional de la cultura Wari, primer imperio.',
    price: 'Desde S/27',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  },
  {
    img: '/img/Escolar/Visita-De-Estudios/puruchucoVisitaSecundaria.webp',
    altImg: 'Imagen de Tour Puruchuco - Visita Secundaria',
    title: 'Puruchuco',
    description: '"El Señor del Sombrero de Plumas" preinca, construcción en parte restaurada y que nos permite ver habitaciones y plazas en muy buen estado, opcional talleres interactivos de cerámica y quipus dentro del museo previa comunicación.',
    price: 'Desde S/22',
    duration: 'En Bus de 40 asientos',
    additionalServices: 'Consultar por adicionales y promociones',
  }
]